export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_AUTH_FAIL = 'USER_AUTH_FAIL';
export const USER_AUTH_LOGOUT = 'USER_AUTH_LOGOUT';
export const USER_AUTH_SIGNUPDONE = 'USER_AUTH_SIGNUPDONE';
